<?php
namespace models;
use base\orm\modelo;
use gamboamartin\errores\errores;
use PDO;
use stdClass;

class ac_centro_educativo extends modelo{
    public function __construct(PDO $link){
        $tabla = __CLASS__;
        $columnas = array($tabla=>false, 'im_registro_patronal' => $tabla, 'dp_calle_pertenece' => $tabla,
            'dp_colonia_postal'=>'dp_calle_pertenece','dp_cp'=>'dp_colonia_postal','dp_municipio'=>'dp_cp',
            'dp_estado'=>'dp_municipio','dp_pais'=>'dp_estado',);
        $campos_obligatorios = array();

        parent::__construct(link: $link,tabla:  $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas);
    }

    public function alta_bd(): array|stdClass
    {
        unset($this->registro['dp_pais_id'],$this->registro['dp_estado_id'],$this->registro['dp_municipio_id'],
            $this->registro['dp_cp_id'],$this->registro['dp_colonia_postal_id']);

        $r_alta =  parent::alta_bd(); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error('Error al dar de alta registro',$r_alta);
        }

        return $r_alta;
    }
}