<?php
namespace gamboamartin\academico\models;
use base\orm\modelo;
use gamboamartin\errores\errores;
use PDO;
use stdClass;

class ac_rvoe extends modelo{
    public function __construct(PDO $link){
        $tabla = 'ac_rvoe';
        $columnas = array($tabla=>false);
        $campos_obligatorios = array();

        parent::__construct(link: $link,tabla:  $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas);

        $this->NAMESPACE = __NAMESPACE__;
    }

    public function alta_bd(): array|stdClass
    {
        $registro = $this->init_data_alta_bd(registro: $this->registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al inicializar registro',data: $registro);
        }

        $this->registro = $registro;

        $r_alta_bd =  parent::alta_bd(); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al dar de alta accion',data: $r_alta_bd);
        }

        return $r_alta_bd;
    }

    private function init_data_alta_bd(array $registro){
        if(!isset($registro['descripcion_select'])) {
            $registro['descripcion_select'] = $registro['codigo'] . ' - ' . $registro['descripcion'];
        }

        if(!isset($registro['alias'])) {
            $registro['alias'] = $registro['numero'];
        }

        return $registro;
    }
}