<?php
/**
 * @author Martin Gamboa Vazquez
 * @version 1.0.0
 * @created 2022-05-14
 * @final En proceso
 *
 */
namespace gamboamartin\academico\controllers;


use gamboamartin\errores\errores;
use gamboamartin\system\links_menu;
use gamboamartin\system\system;
use gamboamartin\template_1\html;
use html\ac_alumno_html;
use models\ac_alumno;
use PDO;
use stdClass;

class controlador_ac_alumno extends system {

    public function __construct(PDO $link, html $html = new \gamboamartin\template_1\html(),
                                stdClass $paths_conf = new stdClass()){

        $modelo = new ac_alumno(link: $link);
        $html_ = new ac_alumno_html($html);
        $obj_link = new links_menu($this->registro_id);
        parent::__construct(html:$html_, link: $link,modelo:  $modelo, obj_link: $obj_link, paths_conf: $paths_conf);

        $this->titulo_lista = 'Alumno';
    }

    public function alta_bd(bool $header, bool $ws = false): array|stdClass
    {
        $this->registro['codigo'] = $this->registro['matricula'];
        $this->registro['descripcion_select'] = $this->registro['matricula'].' '.$this->registro['nombre'].' ';
        $this->registro['descripcion_select'] .= $this->registro['apellido_paterno'].' ';
        $this->registro['descripcion_select'] .= $this->registro['apellido_materno'];
        $alias = $this->registro['apellido_paterno'].' '. $this->registro['apellido_materno'];
        $this->registro['alias'] = strtoupper($alias);
        
        $r_alta_bd = parent::alta_bd($header, $ws);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al dar de alta registro',data:  $r_alta_bd,
                header: $header,ws:$ws);
        }

        return $r_alta_bd;
    }


    public function alta(bool $header, bool $ws = false): array|string
    {
        $r_alta =  parent::alta(header: false); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar template',data:  $r_alta, header: $header,ws:$ws);
        }

        $inputs = (new ac_alumno_html(html: $this->html_base))->genera_inputs_alta(controler: $this, link: $this->link);
        if(errores::$error){
            $error = $this->errores->error(mensaje: 'Error al generar inputs',data:  $inputs);
            print_r($error);
            die('Error');
        }
        return $r_alta;
    }

    public function modifica(bool $header, bool $ws = false, string $breadcrumbs = '', bool $aplica_form = true, bool $muestra_btn = true): array|string
    {
        $r_modifica =  parent::modifica(header: false,aplica_form:  false); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al generar template',data:  $r_modifica);
        }

        $inputs = (new ac_alumno_html(html: $this->html_base))->genera_inputs_modifica(controler: $this, link: $this->link);
        if(errores::$error){
            $error = $this->errores->error(mensaje: 'Error al generar inputs',data:  $inputs);
            print_r($error);
            die('Error');
        }

        return $r_modifica;
    }
}
